#!/bin/sh
echo "Order State Machine Test"
API_PREFIX=localhost:9090/ms-cache/api/v1/order/process/event/
ORDER=e5a5bb0d-6282-4072-9926-a0653095fd07
CUSTOMER=123

curl -X 'POST' "http://localhost:9090/ms-cache/api/v1/order/process/reset/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}CREDIT_CHECKING_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}CREDIT_APPROVED_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}PAYMENT_INIT_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}PAYMENT_APPROVED_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}ORDER_PACKAGE_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}ORDER_READY_TO_SHIP_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}ORDER_SHIPPED_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}ORDER_IN_TRANSIT_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}SEND_FOR_DELIVERY_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''

curl -X 'POST' "http://${API_PREFIX}ORDER_RETURNED_EVENT/customer/${CUSTOMER}/order/${ORDER}" -H 'accept: application/json' -d ''


