#!/bin/sh
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Timeout is set for 5 mins (60*5)
date
echo "gtimeout 300 curl -X 'GET' 'http://localhost:9090/ms-cache/api/v1/kafka/sse/topic1/stream' -H 'accept: text/event-stream'"
gtimeout 300 curl -X 'GET' 'http://localhost:9090/ms-cache/api/v1/kafka/sse/topic1/stream' -H 'accept: text/event-stream'
date
