#!/bin/sh
echo "Reservation State Machine Test"
API_PREFIX=localhost:9090/ms-cache/api/v1/reservation/event/
RESERVATION=b9176b11-d924-495e-a459-3b17687d773e
CUSTOMER=123
# Check if the input is not null
if [ -n "$1" ]; then
    RESERVATION=$1
fi
SLEEP=1

echo "RESET\n"
curl -X 'POST' "http://localhost:9090/ms-cache/api/v1/reservation/reset/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
sleep $SLEEP

echo "\nRESERVATION_VALIDATION_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}RESERVATION_VALIDATION_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nRESERVATION_INIT_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}RESERVATION_INIT_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nHOTEL_BOOKING_REQUEST_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}HOTEL_BOOKING_REQUEST_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nHOTEL_BOOKING_CONFIRMED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}HOTEL_BOOKING_CONFIRMED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nHOTEL_BOOKING_COMPLETED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}HOTEL_BOOKING_COMPLETED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nRENTAL_BOOKING_REQUEST_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}RENTAL_BOOKING_REQUEST_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nRENTAL_BOOKING_CONFIRMED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}RENTAL_BOOKING_CONFIRMED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nRENTAL_BOOKING_COMPLETED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}RENTAL_BOOKING_COMPLETED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''

echo "\nFLIGHT_BOOKING_REQUEST_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}FLIGHT_BOOKING_REQUEST_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nFLIGHT_BOOKING_CONFIRMED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}FLIGHT_BOOKING_CONFIRMED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nFLIGHT_BOOKING_COMPLETED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}FLIGHT_BOOKING_COMPLETED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nPAYMENT_REQUEST_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}PAYMENT_REQUEST_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nPAYMENT_DECLINED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}PAYMENT_DECLINED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nTRIP_CANCELLED_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}TRIP_CANCELLED_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nHOTEL_ROLLBACK_ACK_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}HOTEL_ROLLBACK_ACK_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nRENTAL_ROLLBACK_ACK_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}RENTAL_ROLLBACK_ACK_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nFLIGHT_ROLLBACK_ACK_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}FLIGHT_ROLLBACK_ACK_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP

echo "\nROLLBACK_COMPLETE_EVENT\n"
curl -X 'POST' "http://${API_PREFIX}ROLLBACK_COMPLETE_EVENT/customer/${CUSTOMER}/reservation/${RESERVATION}" -H 'accept: application/json' -d ''
#sleep $SLEEP
